sourceFolder: source
docsFolder: react-styleguidist-master/docs
sourceTypes:
  - md
templatesFolder: templates
assetsFolder: public
publicFolder: public
lang: en
url: 'https://react-styleguidist.js.org/'
title: React Styleguidist
description: Isolated React component development environment with a living style guide
twitter: styleguidist
menu:
  -
    caption: Docs
    href: /docs/getting-started.html
  -
    caption: GitHub
    href: https://github.com/styleguidist/react-styleguidist
  -
    caption: Twitter
    href: https://twitter.com/styleguidist
  -
    caption: Gitter
    href: https://gitter.im/styleguidist/styleguidist
docs:
  -
    caption: Essentials
    pages:
      -
        caption: Get started
        href: /docs/getting-started.html
      -
        caption: Documenting components
        href: /docs/documenting.html
      -
        caption: Locating components
        href: /docs/components.html
      -
        caption: Working with third-parties
        href: /docs/thirdparties.html
      -
        caption: Configuring webpack
        href: /docs/webpack.html
      -
        caption: Cookbook
        href: /docs/cookbook.html
  -
    caption: Advanced
    pages:
      -
        caption: Configuration
        href: /docs/configuration.html
      -
        caption: CLI commands and options
        href: /docs/cli.html
      -
        caption: Node API
        href: /docs/api.html
      -
        caption: Developer guide
        href: /docs/development.html
